# Generated by Django 5.2 on 2025-05-14 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_userid_event_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_rejected',
        ),
    ]
