# Generated by Django 5.2 on 2025-05-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_is_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cancellationPolicy',
        ),
        migrations.AddField(
            model_name='event',
            name='cancellationAvailable',
            field=models.BooleanField(default=False),
        ),
    ]
