# Generated by Django 5.2 on 2025-05-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_cancellationpolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_settled_to_organizer',
            field=models.BooleanField(default=False),
        ),
    ]
