# Generated by Django 5.2 on 2025-05-21 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_cancellationpolicy_and_more'),
        ('wallet', '0003_companywallet_organizerwallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerwallettransaction',
            name='event',
            field=models.ForeignKey(default=234, on_delete=django.db.models.deletion.CASCADE, related_name='organizer_wallet_transactions', to='events.event'),
            preserve_default=False,
        ),
    ]
