# Generated by Django 5.2 on 2025-05-24 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_is_settled_to_organizer'),
        ('wallet', '0004_organizerwallettransaction_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizerwallettransaction',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer_wallet_transactions', to='events.event'),
        ),
    ]
