# Generated by Django 5.2 on 2025-06-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='minimum_purchase_amt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
