# Generated by Django 5.2 on 2025-06-04 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_alter_coupon_valid_from_alter_coupon_valid_to'),
        ('events', '0005_event_is_settled_to_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='eventId',
            field=models.ForeignKey(default='09c0e6f2-6023-4653-b124-15651bc012b7', on_delete=django.db.models.deletion.CASCADE, to='events.event'),
            preserve_default=False,
        ),
    ]
