# Generated by Django 5.2 on 2025-05-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='status',
            new_name='payment_status',
        ),
    ]
