# Generated by Django 5.2 on 2025-05-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_status_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_booking_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
