# Generated by Django 5.2 on 2025-05-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_is_booking_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_name',
            field=models.CharField(default='N/A', max_length=55),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
