# Generated by Django 5.2 on 2025-04-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_phone_users_mobile_users_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
