# Generated by Django 5.2 on 2025-04-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_image',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
