# Generated by Django 5.2 on 2025-04-26 06:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_mobile_alter_users_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryUserOTP',
            fields=[
                ('temp_user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('profile_image', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.TextField()),
                ('otp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
