# Generated by Django 5.2 on 2025-04-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_temporaryuserotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryuserotp',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='temporaryuserotp',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
