# Generated by Django 5.2 on 2025-05-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_blacklistedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedToken',
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='about',
            field=models.TextField(default='temorary'),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='place',
            field=models.CharField(default='temorary', max_length=255),
        ),
        migrations.AlterField(
            model_name='organizerprofile',
            name='id_proof',
            field=models.CharField(default='temorary', max_length=255),
        ),
    ]
