# Generated by Django 5.2 on 2025-05-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_organizerprofile_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
