# Generated by Django 5.2 on 2025-05-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_organizerprofile_rejected_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
