# Generated by Django 5.2 on 2025-05-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_organizerprofile_approved_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizerProfile',
        ),
    ]
