# Generated by Django 5.2 on 2025-05-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_delete_organizerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryUserOTP',
        ),
    ]
